In [348]:
!pip install rdkit

Requirement already satisfied: rdkit in c:\users\dell\anaconda1\lib\site-packages (2022.9.4)
Requirement already satisfied: Pillow in c:\users\dell\anaconda1\lib\site-packages (from rdkit) (9.0.1)
Requirement already satisfied: numpy in c:\users\dell\anaconda1\lib\site-packages (from rdkit) (1.21.5)

In [349]:
conda install -c conda-forge imbalanced-learn

Collecting package metadata (current_repodata.json): ...working... done
Note: you may need to restart the kernel to use updated packages.

Solving environment: ...working... done

# All requested packages already installed.

In [125]:
pip install xgboost==0.90

Collecting xgboost==0.90Note: you may need to restart the kernel to use updated packages.

  Downloading xgboost-0.90-py2.py3-none-win_amd64.whl (18.3 MB)
Requirement already satisfied: numpy in c:\users\dell\anaconda1\lib\site-packages (from xgboost==0.90) (1.21.5)
Requirement already satisfied: scipy in c:\users\dell\anaconda1\lib\site-packages (from xgboost==0.90) (1.7.3)
Installing collected packages: xgboost
Successfully installed xgboost-0.90

In [1]:
!pip install flaml

Requirement already satisfied: flaml in c:\users\dell\anaconda1\lib\site-packages (1.1.3)
Requirement already satisfied: xgboost>=0.90 in c:\users\dell\anaconda1\lib\site-packages (from flaml) (0.90)
Requirement already satisfied: NumPy>=1.17.0rc1 in c:\users\dell\anaconda1\lib\site-packages (from flaml) (1.21.5)
Requirement already satisfied: pandas>=1.1.4 in c:\users\dell\anaconda1\lib\site-packages (from flaml) (1.4.2)
Requirement already satisfied: lightgbm>=2.3.1 in c:\users\dell\anaconda1\lib\site-packages (from flaml) (3.3.5)
Requirement already satisfied: scikit-learn>=0.24 in c:\users\dell\anaconda1\lib\site-packages (from flaml) (1.0.2)
Requirement already satisfied: scipy>=1.4.1 in c:\users\dell\anaconda1\lib\site-packages (from flaml) (1.7.3)
Requirement already satisfied: wheel in c:\users\dell\anaconda1\lib\site-packages (from lightgbm>=2.3.1->flaml) (0.37.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda1\lib\site-packages (from pandas>=1.1.4->flaml) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\dell\anaconda1\lib\site-packages (from pandas>=1.1.4->flaml) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda1\lib\site-packages (from python-dateutil>=2.8.1->pandas>=1.1.4->flaml) (1.16.0)
Requirement already satisfied: joblib>=0.11 in c:\users\dell\anaconda1\lib\site-packages (from scikit-learn>=0.24->flaml) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\dell\anaconda1\lib\site-packages (from scikit-learn>=0.24->flaml) (2.2.0)

In [1]:
import numpy as np 
import pandas as pd
from rdkit import Chem
from rdkit.Chem import Descriptors
from rdkit.Chem.EState import EStateIndices
from rdkit.Chem import rdMolDescriptors
import sklearn
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from rdkit.Chem import AllChem
from rdkit import DataStructs
from flaml import AutoML

from sklearn import metrics
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
#Loading and reading required files
train_data = pd.read_csv('train_II.csv')
test_data = pd.read_csv('test_II.csv')
#feature_data = pd.read_csv('/kaggle/input/the-toxicity-prediction-challenge/feamat.csv')

In [3]:
train_data.head()

                                                Id  Expected
0  C1=CC(=CC=C1C(C2=CC=C(C=C2)O)C(Cl)(Cl)Cl)O;1644         2
1                              CCCCCCCCC(=O)C;2451         2
2        CCCCCCCCCC[N+](C)(C)CCCCCCCCCC.[Cl-];1384         2
3     C1CN(C(=N1)N[N+](=O)[O-])CC2=CN=C(C=C2)Cl;16         2
4                                  [Na+].[I-];1856         2

In [4]:
test_data = test_data.rename(columns = {"x": "Id"})
test_data2=test_data
test_data2.head()

                                                  Id
0                     CC1=CC(=C(C=C1)C(C)(C)C)O;1682
1  CCS(=O)(=O)C1=C(N=CC=C1)S(=O)(=O)NC(=O)NC2=NC(...
2  CC1=NC2=CC=CC=C2N1C3CC4CCC(C3)N4CCC5(CCN(CC5)C...
3                CC1=CC(=O)[N-]S(=O)(=O)O1.[K+];1850
4  CCC(C)(C)C(=O)O[C@H]1C[C@H](C=C2[C@H]1[C@H]([C...

In [5]:
#Splitting Id into 2 separate columns
train_data[["Chemical_Id", "Assay_Id"]] = train_data.Id.str.split(";", expand = True)
test_data[["Chemical_Id", "Assay_Id"]] = test_data.Id.str.split(";", expand = True)
train_data.head()

,Id,Expected,Chemical_Id,Assay_Id
0,C1=CC(=CC=C1C(C2=CC=C(C=C2)O)C(Cl)(Cl)Cl)O;1644,2,C1=CC(=CC=C1C(C2=CC=C(C=C2)O)C(Cl)(Cl)Cl)O,1644
1,CCCCCCCCC(=O)C;2451,2,CCCCCCCCC(=O)C,2451
2,CCCCCCCCCC[N+](C)(C)CCCCCCCCCC.[Cl-];1384,2,CCCCCCCCCC[N+](C)(C)CCCCCCCCCC.[Cl-],1384
3,C1CN(C(=N1)N[N+](=O)[O-])CC2=CN=C(C=C2)Cl;16,2,C1CN(C(=N1)N[N+](=O)[O-])CC2=CN=C(C=C2)Cl,16
4,[Na+].[I-];1856,2,[Na+].[I-],1856

In [6]:
train_data= train_data[train_data.Chemical_Id != 'F[Si-2](F)(F)(F)(F)F.[Na+].[Na+]']
test_data= test_data[test_data.Chemical_Id != 'F[Si-2](F)(F)(F)(F)F.[Na+].[Na+]']

In [7]:
descriptors=[]
for index,rows in train_data.iterrows():
        mol=rows['Chemical_Id']
        array_id=rows['Assay_Id']
        expected=rows['Expected']
        molecule = Chem.MolFromSmiles(mol)
        #fp = AllChem.GetHashedMorganFingerprint(molecule, 2)
        fp = AllChem.GetMorganFingerprintAsBitVect(molecule, 2, nBits=512)
        #array = np.zeros((1, ), dtype=np.int8)
        #DataStructs.ConvertToNumpyArray(fp, array)
        #fp = AllChem.GetMorganFingerprint(molecule,2)
        mw=Descriptors.MolWt(molecule)
        logp= Descriptors.MolLogP(molecule)
        TPSA= Descriptors.TPSA(molecule)
        hbd = Descriptors.NumHDonors(molecule)
        hba = Descriptors.NumHAcceptors(molecule)
        n_rot_bonds = Descriptors.NumRotatableBonds(molecule)
        n_aromatic_rings = Descriptors.NumAromaticRings(molecule)
        n_rings = Descriptors.RingCount(molecule)
        n_heavy_atoms = Descriptors.HeavyAtomCount(molecule)
        frac_sp3 = Descriptors.FractionCSP3(molecule)
        Slogp3=  Descriptors.SlogP_VSA3(molecule)
        Slogp4=  Descriptors.SlogP_VSA4(molecule)
        Slogp5=  Descriptors.SlogP_VSA5(molecule)
        Slogp6=  Descriptors.SlogP_VSA6(molecule)
        Slogp7=  Descriptors.SlogP_VSA7(molecule)
        Smr3 =Descriptors.SMR_VSA3(molecule)
        Smr4 =Descriptors.SMR_VSA4(molecule)
        Smr5 =Descriptors.SMR_VSA5(molecule)
        Smr6 =Descriptors.SMR_VSA6(molecule)



        #narombond = rdMolDescriptors.CalcNumBridgeheadAtoms(molecule)
        #num_aromatic_atoms = len(molecule.GetAromaticAtoms())
        descriptors.append([array_id,fp,expected,mw,logp,TPSA,hbd,hba,n_rot_bonds,n_aromatic_rings,n_rings,n_heavy_atoms,frac_sp3,Slogp3,Slogp4,Slogp5,Slogp6,Slogp7,Smr3,Smr4,Smr5,Smr6])

In [8]:
descriptors1=[]
fp2=[]
for index,rows in test_data.iterrows():
        mol=rows['Chemical_Id']
        array_id=rows['Assay_Id']
        molecule = Chem.MolFromSmiles(mol)
        #fp = AllChem.GetHashedMorganFingerprint(molecule, 2)
        fp = AllChem.GetMorganFingerprintAsBitVect(molecule, 2, nBits=512)
        #array = np.zeros((1, ), dtype=np.int8)
        #DataStructs.ConvertToNumpyArray(fp, array)
        mw=Descriptors.MolWt(molecule)
        logp= Descriptors.MolLogP(molecule)
        TPSA= Descriptors.TPSA(molecule)
        hbd = Descriptors.NumHDonors(molecule)
        hba = Descriptors.NumHAcceptors(molecule)
        n_rot_bonds = Descriptors.NumRotatableBonds(molecule)
        n_aromatic_rings = Descriptors.NumAromaticRings(molecule)
        n_rings = Descriptors.RingCount(molecule)
        n_heavy_atoms = Descriptors.HeavyAtomCount(molecule)
        frac_sp3 = Descriptors.FractionCSP3(molecule)
        Slogp3=  Descriptors.SlogP_VSA3(molecule)
        Slogp4=  Descriptors.SlogP_VSA4(molecule)
        Slogp5=  Descriptors.SlogP_VSA5(molecule)
        Slogp6=  Descriptors.SlogP_VSA6(molecule)
        Slogp7=  Descriptors.SlogP_VSA7(molecule)
        Smr3 =Descriptors.SMR_VSA3(molecule)
        Smr4 =Descriptors.SMR_VSA4(molecule)
        Smr5 =Descriptors.SMR_VSA5(molecule)
        Smr6 =Descriptors.SMR_VSA6(molecule)
        #narombond = rdMolDescriptors.CalcNumBridgeheadAtoms(molecule)
        #num_aromatic_atoms = len(molecule.GetAromaticAtoms())
        descriptors1.append([array_id,fp,mw,logp,TPSA,hbd,hba,n_rot_bonds,n_aromatic_rings,n_rings,n_heavy_atoms,frac_sp3,Slogp3,Slogp4,Slogp5,Slogp6,Slogp7,Smr3,Smr4,Smr5,Smr6])

In [9]:
train_data1=pd.DataFrame(descriptors, columns=['array_id','fp','expected','mw','logp','TPSA','hbd','hba','n_rot_bonds','n_aromatic_rings','n_rings','n_heavy_atoms','frac_sp3','Slog3','Slog4','Slog5','Slog6','Slog7','Smr3','Smr4','Smr5','Smr6'])
test_data1=pd.DataFrame(descriptors1, columns=['array_id','fp','mw','logp','TPSA','hbd','hba','n_rot_bonds','n_aromatic_rings','n_rings','n_heavy_atoms','frac_sp3','Slog3','Slog4','Slog5','Slog6','Slog7','Smr3','Smr4','Smr5','Smr6'])

In [10]:
train_data1.head()

,array_id,fp,expected,mw,logp,TPSA,hbd,hba,n_rot_bonds,n_aromatic_rings,...,frac_sp3,Slog3,Slog4,Slog5,Slog6,Slog7,Smr3,Smr4,Smr5,Smr6
0,1644,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",2,317.599,4.5999,40.46,2,2,2,2,...,0.142857,0.000000,0.000000,17.044809,48.530937,0.00000,0.00000,0.000000,9.710442,0.000000
1,2451,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...",2,156.269,3.3260,17.07,0,1,7,0,...,0.900000,4.794537,0.000000,58.793226,0.000000,0.00000,0.00000,0.000000,58.793226,0.000000
2,1384,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",2,362.086,4.3482,0.00,0,0,18,0,...,1.000000,0.000000,0.000000,116.580620,0.000000,0.00000,0.00000,0.000000,116.580620,27.184857
3,16,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",2,255.665,0.6879,83.66,1,5,3,1,...,0.333333,6.544756,10.114318,5.563451,23.321982,5.15311,15.30968,4.992405,6.544756,13.089513
4,1856,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",2,149.894,-5.9920,0.00,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000

In [11]:
test_data1.head()

,array_id,fp,mw,logp,TPSA,hbd,hba,n_rot_bonds,n_aromatic_rings,n_rings,...,frac_sp3,Slog3,Slog4,Slog5,Slog6,Slog7,Smr3,Smr4,Smr5,Smr6
0,1682,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",164.248,2.99812,20.23,1,1,0,1,1,...,0.454545,5.414990,6.923737,31.898115,18.199101,0.000000,0.000000,0.000000,33.109939,0.000000
1,1656,"[1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ...",431.452,0.19280,166.54,2,10,7,2,2,...,0.285714,19.860544,0.000000,6.923737,34.317388,0.000000,19.674030,0.000000,16.845181,25.289237
2,36,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",696.264,6.61662,87.54,1,6,8,4,7,...,0.444444,15.438282,18.558179,72.733437,65.559154,5.022633,24.072992,0.000000,80.305485,26.681941
3,1850,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",201.244,-2.93050,74.54,0,4,0,0,1,...,0.250000,19.281787,0.000000,6.923737,11.835185,0.000000,0.000000,0.000000,6.923737,0.000000
4,30,"[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",418.574,4.58560,72.83,1,5,6,0,3,...,0.760000,19.062800,29.086615,73.143616,23.801165,0.000000,0.000000,29.086615,91.455515,0.000000

In [12]:
fp_list=[]
for i in range(train_data1.shape[0]):
    array=np.array(train_data1['fp'][i])
    fp_i=pd.DataFrame(array)
    fp_i=fp_i.T
    fp_list.append(fp_i)

len(fp_list)

75377

In [13]:
fp_list1=[]
for i in range(test_data1.shape[0]):
    array=np.array(test_data1['fp'][i])
    fp1_i=pd.DataFrame(array)
    fp1_i=fp1_i.T
    fp_list1.append(fp1_i)

len(fp_list1)

10994

In [14]:
fp_list[0]

,0,1,2,3,4,5,6,7,8,9,...,502,503,504,505,506,507,508,509,510,511
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
df_fp_list=pd.concat(fp_list,ignore_index=True)
df_fp_list

,0,1,2,3,4,5,6,7,8,9,...,502,503,504,505,506,507,508,509,510,511
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75372,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
75373,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
75374,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
75375,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
75376,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
df_fp_list1=pd.concat(fp_list1,ignore_index=True)
df_fp_list1

,0,1,2,3,4,5,6,7,8,9,...,502,503,504,505,506,507,508,509,510,511
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
10990,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10991,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
10992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10993,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
train_final=df_fp_list.join(train_data1,how="outer")
train_final.head()

,0,1,2,3,4,5,6,7,8,9,...,frac_sp3,Slog3,Slog4,Slog5,Slog6,Slog7,Smr3,Smr4,Smr5,Smr6
0,0,1,0,0,0,0,0,0,0,0,...,0.142857,0.000000,0.000000,17.044809,48.530937,0.00000,0.00000,0.000000,9.710442,0.000000
1,0,0,0,0,0,0,0,0,0,0,...,0.900000,4.794537,0.000000,58.793226,0.000000,0.00000,0.00000,0.000000,58.793226,0.000000
2,0,0,0,0,0,0,0,0,0,0,...,1.000000,0.000000,0.000000,116.580620,0.000000,0.00000,0.00000,0.000000,116.580620,27.184857
3,0,0,0,1,0,0,0,0,0,0,...,0.333333,6.544756,10.114318,5.563451,23.321982,5.15311,15.30968,4.992405,6.544756,13.089513
4,0,0,0,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000

In [18]:
test_final=df_fp_list1.join(test_data1,how="outer")
test_final.head()

,0,1,2,3,4,5,6,7,8,9,...,frac_sp3,Slog3,Slog4,Slog5,Slog6,Slog7,Smr3,Smr4,Smr5,Smr6
0,0,0,0,0,0,0,0,0,0,0,...,0.454545,5.414990,6.923737,31.898115,18.199101,0.000000,0.000000,0.000000,33.109939,0.000000
1,1,0,0,0,0,0,0,1,0,0,...,0.285714,19.860544,0.000000,6.923737,34.317388,0.000000,19.674030,0.000000,16.845181,25.289237
2,0,0,0,0,0,0,0,0,0,0,...,0.444444,15.438282,18.558179,72.733437,65.559154,5.022633,24.072992,0.000000,80.305485,26.681941
3,0,0,0,0,0,0,0,0,0,0,...,0.250000,19.281787,0.000000,6.923737,11.835185,0.000000,0.000000,0.000000,6.923737,0.000000
4,1,0,0,0,0,1,0,0,0,0,...,0.760000,19.062800,29.086615,73.143616,23.801165,0.000000,0.000000,29.086615,91.455515,0.000000

In [19]:
train_final=train_final.drop('fp',axis=1)
test_final=test_final.drop('fp',axis=1)

In [20]:
X_train = train_final.drop("expected", axis = 1)
Y_train = train_final["expected"]
X_test  = test_final

X_train['array_id'] = X_train['array_id'].astype(int)
X_test['array_id'] = X_test['array_id'].astype(int)

X_train.shape, Y_train.shape, X_test.shape

((75377, 532), (75377,), (10994, 532))

In [21]:
clf = AutoML()
clf.fit(X_train, Y_train, task="classification", time_budget=7200, estimator_list=['lgbm'])

[flaml.automl.automl: 03-14 09:12:00] {2726} INFO - task = classification
[flaml.automl.automl: 03-14 09:12:00] {2728} INFO - Data split method: stratified
[flaml.automl.automl: 03-14 09:12:00] {2731} INFO - Evaluation method: holdout
[flaml.automl.automl: 03-14 09:12:01] {2858} INFO - Minimizing error metric: 1-roc_auc
[flaml.automl.automl: 03-14 09:12:01] {3004} INFO - List of ML learners in AutoML Run: ['lgbm']
[flaml.automl.automl: 03-14 09:12:01] {3334} INFO - iteration 0, current learner lgbm
[flaml.automl.automl: 03-14 09:12:02] {3472} INFO - Estimated sufficient time budget=24430s. Estimated necessary time budget=24s.
[flaml.automl.automl: 03-14 09:12:02] {3519} INFO -  at 46.7s,	estimator lgbm's best error=0.2632,	best estimator lgbm's best error=0.2632
[flaml.automl.automl: 03-14 09:12:02] {3334} INFO - iteration 1, current learner lgbm
[flaml.automl.automl: 03-14 09:12:02] {3519} INFO -  at 47.0s,	estimator lgbm's best error=0.2632,	best estimator lgbm's best error=0.2632
[flaml.automl.automl: 03-14 09:12:02] {3334} INFO - iteration 2, current learner lgbm
[flaml.automl.automl: 03-14 09:12:02] {3519} INFO -  at 47.3s,	estimator lgbm's best error=0.2464,	best estimator lgbm's best error=0.2464
[flaml.automl.automl: 03-14 09:12:02] {3334} INFO - iteration 3, current learner lgbm
[flaml.automl.automl: 03-14 09:12:02] {3519} INFO -  at 47.6s,	estimator lgbm's best error=0.2067,	best estimator lgbm's best error=0.2067
[flaml.automl.automl: 03-14 09:12:02] {3334} INFO - iteration 4, current learner lgbm
[flaml.automl.automl: 03-14 09:12:03] {3519} INFO -  at 47.9s,	estimator lgbm's best error=0.2067,	best estimator lgbm's best error=0.2067
[flaml.automl.automl: 03-14 09:12:03] {3334} INFO - iteration 5, current learner lgbm
[flaml.automl.automl: 03-14 09:12:03] {3519} INFO -  at 48.1s,	estimator lgbm's best error=0.1837,	best estimator lgbm's best error=0.1837
[flaml.automl.automl: 03-14 09:12:03] {3334} INFO - iteration 6, current learner lgbm
[flaml.automl.automl: 03-14 09:12:03] {3519} INFO -  at 48.4s,	estimator lgbm's best error=0.1837,	best estimator lgbm's best error=0.1837
[flaml.automl.automl: 03-14 09:12:03] {3334} INFO - iteration 7, current learner lgbm
[flaml.automl.automl: 03-14 09:12:04] {3519} INFO -  at 48.6s,	estimator lgbm's best error=0.1837,	best estimator lgbm's best error=0.1837
[flaml.automl.automl: 03-14 09:12:04] {3334} INFO - iteration 8, current learner lgbm
[flaml.automl.automl: 03-14 09:12:04] {3519} INFO -  at 48.9s,	estimator lgbm's best error=0.1687,	best estimator lgbm's best error=0.1687
[flaml.automl.automl: 03-14 09:12:04] {3334} INFO - iteration 9, current learner lgbm
[flaml.automl.automl: 03-14 09:12:04] {3519} INFO -  at 49.2s,	estimator lgbm's best error=0.1687,	best estimator lgbm's best error=0.1687
[flaml.automl.automl: 03-14 09:12:04] {3334} INFO - iteration 10, current learner lgbm
[flaml.automl.automl: 03-14 09:12:05] {3519} INFO -  at 49.9s,	estimator lgbm's best error=0.1360,	best estimator lgbm's best error=0.1360
[flaml.automl.automl: 03-14 09:12:05] {3334} INFO - iteration 11, current learner lgbm
[flaml.automl.automl: 03-14 09:12:06] {3519} INFO -  at 51.6s,	estimator lgbm's best error=0.1360,	best estimator lgbm's best error=0.1360
[flaml.automl.automl: 03-14 09:12:06] {3334} INFO - iteration 12, current learner lgbm
[flaml.automl.automl: 03-14 09:12:07] {3519} INFO -  at 52.2s,	estimator lgbm's best error=0.1360,	best estimator lgbm's best error=0.1360
[flaml.automl.automl: 03-14 09:12:07] {3334} INFO - iteration 13, current learner lgbm
[flaml.automl.automl: 03-14 09:12:08] {3519} INFO -  at 52.9s,	estimator lgbm's best error=0.1360,	best estimator lgbm's best error=0.1360
[flaml.automl.automl: 03-14 09:12:08] {3334} INFO - iteration 14, current learner lgbm
[flaml.automl.automl: 03-14 09:12:09] {3519} INFO -  at 54.5s,	estimator lgbm's best error=0.1360,	best estimator lgbm's best error=0.1360
[flaml.automl.automl: 03-14 09:12:09] {3334} INFO - iteration 15, current learner lgbm
[flaml.automl.automl: 03-14 09:12:12] {3519} INFO -  at 57.1s,	estimator lgbm's best error=0.0869,	best estimator lgbm's best error=0.0869
[flaml.automl.automl: 03-14 09:12:12] {3334} INFO - iteration 16, current learner lgbm
[flaml.automl.automl: 03-14 09:12:15] {3519} INFO -  at 60.0s,	estimator lgbm's best error=0.0869,	best estimator lgbm's best error=0.0869
[flaml.automl.automl: 03-14 09:12:15] {3334} INFO - iteration 17, current learner lgbm
[flaml.automl.automl: 03-14 09:12:19] {3519} INFO -  at 64.5s,	estimator lgbm's best error=0.0869,	best estimator lgbm's best error=0.0869
[flaml.automl.automl: 03-14 09:12:19] {3334} INFO - iteration 18, current learner lgbm
[flaml.automl.automl: 03-14 09:12:25] {3519} INFO -  at 69.8s,	estimator lgbm's best error=0.0762,	best estimator lgbm's best error=0.0762
[flaml.automl.automl: 03-14 09:12:25] {3334} INFO - iteration 19, current learner lgbm
[flaml.automl.automl: 03-14 09:12:29] {3519} INFO -  at 73.7s,	estimator lgbm's best error=0.0762,	best estimator lgbm's best error=0.0762
[flaml.automl.automl: 03-14 09:12:29] {3334} INFO - iteration 20, current learner lgbm
[flaml.automl.automl: 03-14 09:12:32] {3519} INFO -  at 77.2s,	estimator lgbm's best error=0.0762,	best estimator lgbm's best error=0.0762
[flaml.automl.automl: 03-14 09:12:32] {3334} INFO - iteration 21, current learner lgbm
[flaml.automl.automl: 03-14 09:12:51] {3519} INFO -  at 96.2s,	estimator lgbm's best error=0.0725,	best estimator lgbm's best error=0.0725
[flaml.automl.automl: 03-14 09:12:51] {3334} INFO - iteration 22, current learner lgbm
[flaml.automl.automl: 03-14 09:13:09] {3519} INFO -  at 113.8s,	estimator lgbm's best error=0.0725,	best estimator lgbm's best error=0.0725
[flaml.automl.automl: 03-14 09:13:09] {3334} INFO - iteration 23, current learner lgbm
[flaml.automl.automl: 03-14 09:13:23] {3519} INFO -  at 128.4s,	estimator lgbm's best error=0.0725,	best estimator lgbm's best error=0.0725
[flaml.automl.automl: 03-14 09:13:23] {3334} INFO - iteration 24, current learner lgbm
[flaml.automl.automl: 03-14 09:13:36] {3519} INFO -  at 141.5s,	estimator lgbm's best error=0.0725,	best estimator lgbm's best error=0.0725
[flaml.automl.automl: 03-14 09:13:36] {3334} INFO - iteration 25, current learner lgbm
[flaml.automl.automl: 03-14 09:14:00] {3519} INFO -  at 165.3s,	estimator lgbm's best error=0.0725,	best estimator lgbm's best error=0.0725
[flaml.automl.automl: 03-14 09:14:00] {3334} INFO - iteration 26, current learner lgbm
[flaml.automl.automl: 03-14 09:14:46] {3519} INFO -  at 210.9s,	estimator lgbm's best error=0.0725,	best estimator lgbm's best error=0.0725
[flaml.automl.automl: 03-14 09:14:46] {3334} INFO - iteration 27, current learner lgbm
[flaml.automl.automl: 03-14 09:14:55] {3519} INFO -  at 220.5s,	estimator lgbm's best error=0.0725,	best estimator lgbm's best error=0.0725
[flaml.automl.automl: 03-14 09:14:55] {3334} INFO - iteration 28, current learner lgbm
[flaml.automl.automl: 03-14 09:15:47] {3519} INFO -  at 271.8s,	estimator lgbm's best error=0.0725,	best estimator lgbm's best error=0.0725
[flaml.automl.automl: 03-14 09:15:47] {3334} INFO - iteration 29, current learner lgbm
[flaml.automl.automl: 03-14 09:15:52] {3519} INFO -  at 276.7s,	estimator lgbm's best error=0.0725,	best estimator lgbm's best error=0.0725
[flaml.automl.automl: 03-14 09:15:52] {3334} INFO - iteration 30, current learner lgbm
[flaml.automl.automl: 03-14 09:15:57] {3519} INFO -  at 282.6s,	estimator lgbm's best error=0.0725,	best estimator lgbm's best error=0.0725
[flaml.automl.automl: 03-14 09:15:57] {3334} INFO - iteration 31, current learner lgbm
[flaml.automl.automl: 03-14 09:16:44] {3519} INFO -  at 329.6s,	estimator lgbm's best error=0.0725,	best estimator lgbm's best error=0.0725
[flaml.automl.automl: 03-14 09:16:44] {3334} INFO - iteration 32, current learner lgbm
[flaml.automl.automl: 03-14 09:16:51] {3519} INFO -  at 335.7s,	estimator lgbm's best error=0.0725,	best estimator lgbm's best error=0.0725
[flaml.automl.automl: 03-14 09:16:51] {3334} INFO - iteration 33, current learner lgbm
[flaml.automl.automl: 03-14 09:17:04] {3519} INFO -  at 348.7s,	estimator lgbm's best error=0.0719,	best estimator lgbm's best error=0.0719

[flaml.automl.automl: 03-14 09:17:04] {3334} INFO - iteration 34, current learner lgbm
[flaml.automl.automl: 03-14 09:17:17] {3519} INFO -  at 362.6s,	estimator lgbm's best error=0.0681,	best estimator lgbm's best error=0.0681
[flaml.automl.automl: 03-14 09:17:17] {3334} INFO - iteration 35, current learner lgbm
[flaml.automl.automl: 03-14 09:17:28] {3519} INFO -  at 373.5s,	estimator lgbm's best error=0.0681,	best estimator lgbm's best error=0.0681
[flaml.automl.automl: 03-14 09:17:28] {3334} INFO - iteration 36, current learner lgbm
[flaml.automl.automl: 03-14 09:18:36] {3519} INFO -  at 441.6s,	estimator lgbm's best error=0.0681,	best estimator lgbm's best error=0.0681
[flaml.automl.automl: 03-14 09:18:36] {3334} INFO - iteration 37, current learner lgbm
[flaml.automl.automl: 03-14 09:18:39] {3519} INFO -  at 444.4s,	estimator lgbm's best error=0.0681,	best estimator lgbm's best error=0.0681
[flaml.automl.automl: 03-14 09:18:39] {3334} INFO - iteration 38, current learner lgbm
[flaml.automl.automl: 03-14 09:19:17] {3519} INFO -  at 482.4s,	estimator lgbm's best error=0.0681,	best estimator lgbm's best error=0.0681
[flaml.automl.automl: 03-14 09:19:17] {3334} INFO - iteration 39, current learner lgbm
[flaml.automl.automl: 03-14 09:19:31] {3519} INFO -  at 495.7s,	estimator lgbm's best error=0.0681,	best estimator lgbm's best error=0.0681
[flaml.automl.automl: 03-14 09:19:31] {3334} INFO - iteration 40, current learner lgbm
[flaml.automl.automl: 03-14 09:25:04] {3519} INFO -  at 829.0s,	estimator lgbm's best error=0.0681,	best estimator lgbm's best error=0.0681
[flaml.automl.automl: 03-14 09:25:04] {3334} INFO - iteration 41, current learner lgbm
[flaml.automl.automl: 03-14 09:25:08] {3519} INFO -  at 833.3s,	estimator lgbm's best error=0.0681,	best estimator lgbm's best error=0.0681
[flaml.automl.automl: 03-14 09:25:08] {3334} INFO - iteration 42, current learner lgbm
[flaml.automl.automl: 03-14 09:25:15] {3519} INFO -  at 839.9s,	estimator lgbm's best error=0.0681,	best estimator lgbm's best error=0.0681
[flaml.automl.automl: 03-14 09:25:15] {3334} INFO - iteration 43, current learner lgbm
[flaml.automl.automl: 03-14 09:28:58] {3519} INFO -  at 1063.0s,	estimator lgbm's best error=0.0671,	best estimator lgbm's best error=0.0671
[flaml.automl.automl: 03-14 09:28:58] {3334} INFO - iteration 44, current learner lgbm
[flaml.automl.automl: 03-14 09:39:49] {3519} INFO -  at 1713.7s,	estimator lgbm's best error=0.0671,	best estimator lgbm's best error=0.0671
[flaml.automl.automl: 03-14 09:39:49] {3334} INFO - iteration 45, current learner lgbm
[flaml.automl.automl: 03-14 09:41:50] {3519} INFO -  at 1834.7s,	estimator lgbm's best error=0.0671,	best estimator lgbm's best error=0.0671
[flaml.automl.automl: 03-14 09:41:50] {3334} INFO - iteration 46, current learner lgbm
[flaml.automl.automl: 03-14 09:42:40] {3519} INFO -  at 1884.7s,	estimator lgbm's best error=0.0671,	best estimator lgbm's best error=0.0671
[flaml.automl.automl: 03-14 09:42:40] {3334} INFO - iteration 47, current learner lgbm
[flaml.automl.automl: 03-14 10:23:24] {3519} INFO -  at 4329.5s,	estimator lgbm's best error=0.0671,	best estimator lgbm's best error=0.0671
[flaml.automl.automl: 03-14 10:23:24] {3334} INFO - iteration 48, current learner lgbm
[flaml.automl.automl: 03-14 10:24:03] {3519} INFO -  at 4368.1s,	estimator lgbm's best error=0.0671,	best estimator lgbm's best error=0.0671
[flaml.automl.automl: 03-14 10:24:03] {3334} INFO - iteration 49, current learner lgbm
[flaml.automl.automl: 03-14 10:51:25] {3519} INFO -  at 6010.4s,	estimator lgbm's best error=0.0671,	best estimator lgbm's best error=0.0671
[flaml.automl.automl: 03-14 10:51:25] {3334} INFO - iteration 50, current learner lgbm
[flaml.automl.automl: 03-14 10:51:41] {3519} INFO -  at 6026.2s,	estimator lgbm's best error=0.0671,	best estimator lgbm's best error=0.0671
[flaml.automl.automl: 03-14 10:51:41] {3334} INFO - iteration 51, current learner lgbm
[flaml.automl.automl: 03-14 11:13:02] {3519} INFO -  at 7306.7s,	estimator lgbm's best error=0.0671,	best estimator lgbm's best error=0.0671
[flaml.automl.automl: 03-14 11:21:07] {3783} INFO - retrain lgbm for 485.1s
[flaml.automl.automl: 03-14 11:21:07] {3790} INFO - retrained model: LGBMClassifier(colsample_bytree=0.7708545486048289,
               learning_rate=0.0032882572946612678, max_bin=1023,
               min_child_samples=8, n_estimators=3270, num_leaves=297,
               reg_alpha=0.0043079524523839995, reg_lambda=0.030766708909660292,
               verbose=-1)
[flaml.automl.automl: 03-14 11:21:07] {3034} INFO - fit succeeded
[flaml.automl.automl: 03-14 11:21:07] {3035} INFO - Time taken to find the best model: 1062.981618642807

In [22]:
y_pred_train = clf.predict(X_train)
y_pred = clf.predict(X_test)

In [23]:
print('Accuracy: %.3f' % metrics.accuracy_score(Y_train, y_pred_train))

Accuracy: 0.973

In [24]:
print(metrics.classification_report(Y_train, y_pred_train))

              precision    recall  f1-score   support

           1       0.96      0.84      0.90     10658
           2       0.97      0.99      0.98     64719

    accuracy                           0.97     75377
   macro avg       0.97      0.92      0.94     75377
weighted avg       0.97      0.97      0.97     75377

In [25]:
output = pd.DataFrame({'Id': test_data2['Id'], 'Predicted': y_pred})
output.to_csv('submission2_a_all.csv',index=False)